### PR TITLE
Issue 16

### PR DESCRIPTION
**Pull request by TammyHale**
Rob, 

I have created the preliminary export/import functionality for workspaces. I have a few questions:

1. How would you like xquery code tested in this project? I started going down the path of invoking xquery unit tests from junit, but wasn't sure that's how we'd ultimately go so I stopped. Do we want to use an xquery unit testing framework? 
2. How should the xquery import/export functionality be invoked? I assume from Java, but was wondering how it should be organized. 
3. The import functionality is mostly copied from qconsole-model.xqy in the MarkLogic Server code. I did this because there is no way to specify the user for whom you want to import a workspace. It defaults to using the current user. Do you have any recommendations where I wouldn't be copying an entire function just to change one line? 

I still have work to do on all of this. It's by no means complete. I look forward to your sweeping feedback.

Tammy

### CODE REVIEW

**Comment by rjrudin** [comment]
Tammy – I think the next step would be baking this into easy-to-use Gradle commands. Looking for you and Scott’s input on this. I’m imagining the following:

1.	A Gradle task that allows me to easily export one (or more?) workspaces to a directory in my project structure. 
o	That directory could be under src/main/ml-config, but I kind of like doing data/qc-workspaces instead. It’s not part of config really – it’s not loaded via the Mgmt API – it’s really a dataset that you load into a database.
2.	A Gradle task that allows me to easily import into qconsole one or more workspaces from that directory in my project structure

So then e.g. Tammy could run the #1 task – “gradle mlExportWorkspace –PworkspaceName=firstOne” – and it would be written out to data/qc-workspaces/firstOne.xml. The actual code doing the work is what I believe Tammy has written already, and that could be executed against the XDBC server on port 8000. 

And then I could run the #2 task – e.g. “gradle mlImportWorkspace –PworkspaceName=firstOne” – and that would make an XCC call to port 8000 and run Tammy’s code for importing workspaces.

How does that all sound?

**Comment by TammyHale** [comment]
Works for me. Should I add these requirements to issue 16 or would it make more sense to create a new one?

Did you see my comments/questions with the pull request? I asked for input on if you wanted xquery unit tested through junit or an xquery unit testing framework. Also asked for input about the fact that I had to copy an entire function from ML server code to change one line.

**Comment by sastafford** [comment]
Tammy, I would start with having a unit test that just verifies a workspace exists in the App-Server database.  When we would call gradle test, we would have to pass in the port number and database name specific for the App-Services database.  That database is where the workspace resides.

**Comment by TammyHale** [comment]
Scott, did you look at the code?

**Comment by sastafford** [comment]
I just re-read my comments and I can understand the confusion.  That's what I get when trying to multi-task.  I was trying to give some advice with regards to the unit test.  If you choose to use Java for your unit test, I would be content if all the unit test would do is to verify that the Workspace document made it into the App-Services database.  But to do that you are going to have to explicitly state the unit test to run against that database and not the default content (or application) database.  

With regards to using gradle to actually triggering the workspace imports, I am fine with Rob's suggestion above.

**Comment by TammyHale** [comment]
In both modules, I do an eval against the App-Services database for workspace queries. Thanks for your input.

**Pull request closed without merging**
